### PR TITLE
fix: add latest sso and controltower filters for aws-nuke

### PR DESCRIPTION
**Pull request by mavogel**
Signed-off-by: Manuel Vogel <mavogel@posteo.de>

## Issue: 
related to #5 

## Description of changes:*
- update to latest changes on `aws-nuke` config for:
  - sso
  - controltower

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by moellr** [comment]
Not merging this PR as it contains an accidental error. Nevertheless I already applied the valid changes by another commit, so I am closing this PR.

**Comment by mavogel** [comment]
Hi Rainer, this PR is an extension of #5 . You mean the fix of the `Makefile` in https://github.com/awslabs/sandbox-accounts-for-events/commit/47cf790b9791b2786e2ab685cccc93cd64b847b2, right? I can fix it and update this PR? WDTY?

**Comment by moellr** [comment]
Thx for your suggestion, I already did this 2 weeks ago, as we had a user who was in urgent request of your changes. All you changes have made it into the codebase, I merged your commits (and uncommented the still required line in the Makefile before).
All updates done, thx a lot for your valuable contribution. Keep up the good work. 👍

**Comment by mavogel** [comment]
Hmm correct me if I am wrong, however, e.g I cannot see the change

```yaml
presets:
  sso:
    filters:
      IAMSAMLProvider:
        - type: "regex"
          value: "AWSSSO_.*_DO_NOT_DELETE"
      IAMRole:
        - type: "glob"
          value: "AWSReservedSSO_*"
      IAMRolePolicyAttachment:
        - type: "glob"
          value: "AWSReservedSSO_*"
      IAMRolePolicy: # <= This change!!! 
        - type: "glob"
          value: "AWSReservedSSO_*"
```

in the master branch https://github.com/awslabs/sandbox-accounts-for-events/blob/main/dce-integration/cmd/codebuild/reset/default-nuke-config-template.yml#L52. Or am I wrong?

**Comment by moellr** [comment]
Help me, I cannot find the IAMRolePolicy in your PR: https://github.com/awslabs/sandbox-accounts-for-events/pull/5/files
Nevertheless adding the Policy totally makes sense, agreed. Feel free to add it + create a PR.

**Pull request closed without merging**
